# Generated by Django 5.0.1 on 2024-11-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='N/A', max_length=200)),
                ('destination', models.CharField(default='N/A', max_length=200)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('ratings', models.IntegerField(default=0)),
                ('rider', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('is_cancelled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('is_rider', models.IntegerField(default=0)),
                ('is_ready', models.IntegerField(default=0)),
                ('ride', models.IntegerField(default=-1)),
            ],
        ),
    ]
